events {
    worker_connections 1024;
}

http {
    # --------------------------------------------------------
    # FRONTEND: Route mydomain.com & www.mydomain.com to Next.js
    # --------------------------------------------------------
    server {
        listen 80;
        server_name sahibshakhayev.tech www.sahibshakhayev.tech;

        location / {
            proxy_pass http://frontend:3000;
            
            # Pass standard headers so Next.js knows the real client IP
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # --------------------------------------------------------
    # BACKEND: Route api.mydomain.com to FastAPI
    # --------------------------------------------------------
    server {
        listen 80;
        server_name api.sahibshakhayev.tech;

        location / {
            proxy_pass http://backend:8000;
            
            # Pass standard headers to FastAPI
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}